apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: iqs-positron
  name: iqs-bindles-infrastructure-node-deploy
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: iqs-bindles-infrastructure-node
    spec: 
      containers:
      - name: iqs-bindles-infrastructure-node-pod
        image: registry.gitlab.com/iqs-bindles/iqs-bindles-infrastructure-node:1.0.0-1-rc
        ports:
        - containerPort: 8080
          name: infrastructure
        env:
        - name: ENV_NAME
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: env_name
        - name: MONGO_ENABLED
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: mongo_enabled
        - name: MONGO_SERVICE_URI
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: mongo_service_uri
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: aws_region
        - name: AWS_ACCESS_ID
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: aws_access_id
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: aws_access_key
        - name: MAGIC_CODE
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: magic_code
        - name: AWS_BLOBS_ARN
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: aws_blobs_arn
        - name: EMAIL_SERVICE
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: email_service
        - name: EMAIL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: email_service_host
        - name: EMAIL_SSL
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: email_ssl
        - name: EMAIL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: email_service_port
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: email_user
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: iqs-positron-secret
              key: email_password
        - name: EMAIL_FROM
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: email_from
        - name: EMAIL_SIGNATURE
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: email_signature
        - name: CLIENT_URL
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: client_url
        - name: CLIENT_NAME
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: client_name
        - name: SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: server_url
        - name: SMS_FROM
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: sms_from
        - name: SMS_SIGNATURE
          valueFrom:
            configMapKeyRef:
              name: iqs-positron-config
              key: sms_signature
        readinessProbe:
          httpGet:
            path: /heartbeat
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 40
          timeoutSeconds: 6
      imagePullSecrets:
      - name: gitlab-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  namespace: iqs-positron
  name: iqs-bindles-infrastructure
  labels: 
    app: iqs-bindles-infrastructure-node
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    protocol: TCP
    name: infrastructure
  selector:
    app: iqs-bindles-infrastructure-node